version: '3'

services:
  frontend:
    container_name: "react_spa"
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd frontend && npm run start'
    ports:
      - '3000:3000'
    tty: true
